/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BazaPodataka.DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jasmin
 */
public class Ambulanta extends javax.swing.JFrame {

    /**
     * Creates new form GlavniProzor
     */
    public Ambulanta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBrisanjeAmbulanti = new javax.swing.JTabbedPane();
        paneDodavanjeAmb = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNazivAmb = new javax.swing.JTextField();
        txtAdresaAmb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDodajAmb = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprikazAmb = new javax.swing.JTable();
        btnPrikaziAmb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtObrisiAmb = new javax.swing.JTextField();
        btnObrisiAmb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ambulanta");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Dodavanje ambulanti");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Naziv ambulante: ");

        txtNazivAmb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtAdresaAmb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Adresa:");

        btnDodajAmb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDodajAmb.setText("Dodaj");
        btnDodajAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajAmbActionPerformed(evt);
            }
        });

        paneDodavanjeAmb.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneDodavanjeAmb.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneDodavanjeAmb.setLayer(txtNazivAmb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneDodavanjeAmb.setLayer(txtAdresaAmb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneDodavanjeAmb.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        paneDodavanjeAmb.setLayer(btnDodajAmb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneDodavanjeAmbLayout = new javax.swing.GroupLayout(paneDodavanjeAmb);
        paneDodavanjeAmb.setLayout(paneDodavanjeAmbLayout);
        paneDodavanjeAmbLayout.setHorizontalGroup(
            paneDodavanjeAmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneDodavanjeAmbLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(paneDodavanjeAmbLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(paneDodavanjeAmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneDodavanjeAmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneDodavanjeAmbLayout.createSequentialGroup()
                        .addComponent(btnDodajAmb)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneDodavanjeAmbLayout.createSequentialGroup()
                        .addGroup(paneDodavanjeAmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNazivAmb, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtAdresaAmb))
                        .addGap(221, 221, 221))))
        );
        paneDodavanjeAmbLayout.setVerticalGroup(
            paneDodavanjeAmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneDodavanjeAmbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(paneDodavanjeAmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneDodavanjeAmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdresaAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDodajAmb)
                .addGap(133, 133, 133))
        );

        paneBrisanjeAmbulanti.addTab("Dodavanje ambulanti", paneDodavanjeAmb);

        tblprikazAmb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Adresa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblprikazAmb);

        btnPrikaziAmb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnPrikaziAmb.setText("Prikazi");
        btnPrikaziAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziAmbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Unesite id ambulante za obrisati: ");

        txtObrisiAmb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnObrisiAmb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnObrisiAmb.setText("Obrisi");
        btnObrisiAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiAmbActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnPrikaziAmb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtObrisiAmb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnObrisiAmb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(btnPrikaziAmb)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnObrisiAmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtObrisiAmb))
                .addGap(134, 328, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnPrikaziAmb)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtObrisiAmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnObrisiAmb)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        paneBrisanjeAmbulanti.addTab("Prikaz ambulanti", jLayeredPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBrisanjeAmbulanti)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBrisanjeAmbulanti)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajAmbActionPerformed
        // TODO add your handling code here:
        String naziv = txtNazivAmb.getText();
        String adresa = txtAdresaAmb.getText();
        DB.unosAmbulante(naziv, adresa);
        txtNazivAmb.setText("");
        txtAdresaAmb.setText("");
    }//GEN-LAST:event_btnDodajAmbActionPerformed

    private void btnPrikaziAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziAmbActionPerformed
        // TODO add your handling code here:
        
        Connection con = null;
        Statement st = null;
        String upit = "select * from ambulanta";
        ResultSet rs = null;
        try{
            con = DB.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(upit);
            DefaultTableModel t = (DefaultTableModel)tblprikazAmb.getModel();
                t.getDataVector().removeAllElements();
            while(rs.next())
            {
                String naziv = rs.getString("naziv");
                String adresa = rs.getString("adresa");
                String id = String.valueOf(rs.getInt("id"));
                String podaci[] = {id, naziv, adresa};
                
                DefaultTableModel tabela = (DefaultTableModel)tblprikazAmb.getModel();
                
                tabela.addRow(podaci);
                
            }
        }
        catch(SQLException e)
        {
            
        }
    }//GEN-LAST:event_btnPrikaziAmbActionPerformed

    private void btnObrisiAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiAmbActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(txtObrisiAmb.getText());
        Statement st = null;
        Connection con = null;
        String upit1 = "delete from radnik where ambulanta_id = '"+id+"'";
        String upit2 = "delete from ambulanta where id = '"+id+"'";
        try
        {
            con = DB.getConnection();
            st = con.createStatement();
            st.executeUpdate(upit1);
            st.close();
            st = con.createStatement();
            st.executeUpdate(upit2);
            st.close();
            con.close();
            txtObrisiAmb.setText("");
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnObrisiAmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ambulanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ambulanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ambulanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ambulanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ambulanta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajAmb;
    private javax.swing.JButton btnObrisiAmb;
    private javax.swing.JButton btnPrikaziAmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane paneBrisanjeAmbulanti;
    private javax.swing.JLayeredPane paneDodavanjeAmb;
    private javax.swing.JTable tblprikazAmb;
    private javax.swing.JTextField txtAdresaAmb;
    private javax.swing.JTextField txtNazivAmb;
    private javax.swing.JTextField txtObrisiAmb;
    // End of variables declaration//GEN-END:variables
}
